#! /bin/bash
### This file is used to define kvantum and gtk4/libadwaita Themes for GNOME
## Set kvantum Themes

# Set the kvantum theme gnome uses when in dark mode
# Example: KVANTUM_THEME_DARK=Orchis-dark

KVANTUM_THEME_DARK=Orchis-dark

# Set the kvantum theme gnome uses when in light mode
# Example: KVANTUM_THEME_LIGHT=Orchis

KVANTUM_THEME_LIGHT=Orchis

## Set GTK4/libadwaita Themes (Use PATHs)

# Set the GTK4/libadwaita theme gnome uses when in dark mode
# Example: GTK_THEME_PATH_DARK=/usr/share/Orchis-Dark

GTK_THEME_PATH_DARK=/usr/share/themes/"$(dconf read /org/gnome/desktop/interface/gtk-theme | sed "s+'++" | sed "s+'++" | sed "s+-Dark++" | sed "s+-Light++")"-Dark

# Set the GTK4/libadwaita theme gnome uses when in lightmode
# Example: GTK_THEME_PATH_LIGHT=/usr/share/Orchis-Light

GTK_THEME_PATH_LIGHT=/usr/share/themes/"$(dconf read /org/gnome/desktop/interface/gtk-theme | sed "s+'++" | sed "s+'++" | sed "s+-Dark++" | sed "s+-Light++")"-Light
